language: node_js
node_js:
  - "stable"

env:
  - CC_TEST_REPORTER_ID=1ea5b6ed2442568c25444c1626fdaead02f6a28165ed90c6c6c3e1dea22a6702

cache:
  directories:
    - "node_modules"

script:
  - npm test

after_script:
  - npm run coverage